pipeline {
    agent {
       node {
          label 'AGENT-1'
       }
    }
    environment {
         COURSE = "jenkins"
         appVersion = ""
    }
    options {
        timeout(time: 10, unit: 'MINUTES') 
        disableConcurrentBuilds()
    }
   
    // This is building stage
    stages {
       stage('Read Version')  {
         steps {
           script {
             def packageJSON = readJSON file: 'package.json'
             appVersion = packageJSON.Version
             echo "app version : ${appVersion}"
           }
         }
       }
       // This is Testing stage
        stage('Test') { 
          steps {
            script {
              sh """
                 echo "By using the Hybrid method testing the pipeline"
                 echo $COURSE
                 
                 """
            }
           
          }
        }
        stage('Deploy') {
           steps {
             script {
                sh """
                echo "By using the Hybrid method deploying the pipeline"
                echo $COURSE
                """
             }
           }
        }
//  This is post build
    }
    post {
        always {
            echo "I always say Hello..!"
            cleanWs()
        }
        success {
             echo "i will run if successfull"
        }
        failure {
             echo "i will run if failure"
        }
    }
     
}